/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAssemblyRouteImport } from './routes/_authenticated.assembly'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedFactoryWallboardRouteImport } from './routes/_authenticated.factory-wallboard'
import { Route as AuthenticatedForcePasswordChangeRouteImport } from './routes/_authenticated.force-password-change'
import { Route as AuthenticatedPickingRouteImport } from './routes/_authenticated.picking'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated.production'
import { Route as AuthenticatedShippingRouteImport } from './routes/_authenticated.shipping'
import { Route as AuthenticatedTechnicalAssistanceRouteImport } from './routes/_authenticated.technical-assistance'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated.settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssemblyRoute = AuthenticatedAssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFactoryWallboardRoute =
  AuthenticatedFactoryWallboardRouteImport.update({
    id: '/factory-wallboard',
    path: '/factory-wallboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForcePasswordChangeRoute =
  AuthenticatedForcePasswordChangeRouteImport.update({
    id: '/force-password-change',
    path: '/force-password-change',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPickingRoute = AuthenticatedPickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShippingRoute = AuthenticatedShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTechnicalAssistanceRoute =
  AuthenticatedTechnicalAssistanceRouteImport.update({
    id: '/technical-assistance',
    path: '/technical-assistance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assembly': typeof AuthenticatedAssemblyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/factory-wallboard': typeof AuthenticatedFactoryWallboardRoute
  '/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/picking': typeof AuthenticatedPickingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/shipping': typeof AuthenticatedShippingRoute
  '/technical-assistance': typeof AuthenticatedTechnicalAssistanceRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assembly': typeof AuthenticatedAssemblyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/factory-wallboard': typeof AuthenticatedFactoryWallboardRoute
  '/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/picking': typeof AuthenticatedPickingRoute
  '/production': typeof AuthenticatedProductionRoute
  '/shipping': typeof AuthenticatedShippingRoute
  '/technical-assistance': typeof AuthenticatedTechnicalAssistanceRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/assembly': typeof AuthenticatedAssemblyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/factory-wallboard': typeof AuthenticatedFactoryWallboardRoute
  '/_authenticated/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/_authenticated/picking': typeof AuthenticatedPickingRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/shipping': typeof AuthenticatedShippingRoute
  '/_authenticated/technical-assistance': typeof AuthenticatedTechnicalAssistanceRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assembly'
    | '/dashboard'
    | '/factory-wallboard'
    | '/force-password-change'
    | '/picking'
    | '/production'
    | '/shipping'
    | '/technical-assistance'
    | '/projects/$projectId'
    | '/settings/users'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assembly'
    | '/dashboard'
    | '/factory-wallboard'
    | '/force-password-change'
    | '/picking'
    | '/production'
    | '/shipping'
    | '/technical-assistance'
    | '/projects/$projectId'
    | '/settings/users'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/assembly'
    | '/_authenticated/dashboard'
    | '/_authenticated/factory-wallboard'
    | '/_authenticated/force-password-change'
    | '/_authenticated/picking'
    | '/_authenticated/production'
    | '/_authenticated/shipping'
    | '/_authenticated/technical-assistance'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/users'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assembly': {
      id: '/_authenticated/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AuthenticatedAssemblyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/factory-wallboard': {
      id: '/_authenticated/factory-wallboard'
      path: '/factory-wallboard'
      fullPath: '/factory-wallboard'
      preLoaderRoute: typeof AuthenticatedFactoryWallboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/force-password-change': {
      id: '/_authenticated/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof AuthenticatedForcePasswordChangeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/picking': {
      id: '/_authenticated/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof AuthenticatedPickingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipping': {
      id: '/_authenticated/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AuthenticatedShippingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/technical-assistance': {
      id: '/_authenticated/technical-assistance'
      path: '/technical-assistance'
      fullPath: '/technical-assistance'
      preLoaderRoute: typeof AuthenticatedTechnicalAssistanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssemblyRoute: typeof AuthenticatedAssemblyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFactoryWallboardRoute: typeof AuthenticatedFactoryWallboardRoute
  AuthenticatedForcePasswordChangeRoute: typeof AuthenticatedForcePasswordChangeRoute
  AuthenticatedPickingRoute: typeof AuthenticatedPickingRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedShippingRoute: typeof AuthenticatedShippingRoute
  AuthenticatedTechnicalAssistanceRoute: typeof AuthenticatedTechnicalAssistanceRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssemblyRoute: AuthenticatedAssemblyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFactoryWallboardRoute: AuthenticatedFactoryWallboardRoute,
  AuthenticatedForcePasswordChangeRoute: AuthenticatedForcePasswordChangeRoute,
  AuthenticatedPickingRoute: AuthenticatedPickingRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedShippingRoute: AuthenticatedShippingRoute,
  AuthenticatedTechnicalAssistanceRoute: AuthenticatedTechnicalAssistanceRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
